[package]
name = "nyx-mailbox-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rusqlite.workspace = true
arti-client.workspace = true
tor-hsservice.workspace = true
tor-cell.workspace = true
tor-proto.workspace = true
safelog.workspace = true
nyx-protocol = { path = "../../crates/nyx-protocol" }
dotenvy.workspace = true
