[package]
name = "nyx-tor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
arti-client.workspace = true
tor-rtcompat.workspace = true
tor-hsservice.workspace = true
futures.workspace = true
nyx-protocol = { path = "../nyx-protocol" }
nyx-store = { path = "../nyx-store" }
