[package]
name = "nyx-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dioxus.workspace = true
nyx-crypto = { path = "../nyx-crypto" }
nyx-store = { path = "../nyx-store" }
nyx-tor = { path = "../nyx-tor" }
tokio.workspace = true
zeroize.workspace = true
dotenvy.workspace = true
