[package]
name = "nyx-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rusqlite.workspace = true
argon2.workspace = true
chacha20poly1305.workspace = true
zeroize.workspace = true
rand.workspace = true
tempfile.workspace = true
uuid.workspace = true
nyx-protocol = { path = "../nyx-protocol" }
